env:
    global:
        - PROJECT_ROOT=`pwd`
        - secure: "XbO6qScVisfU4rdnEHOFgGpuTyiRxxlbUOFnK0x4Pu5oMjasth42ysW3WU4GnIhra1wxUmWFydBfdhpRTE6YUuzdHNclF2IzW7RGB/+agNkGkYX6sAXMVCszXh9Ue8D+lc/LCcErH0D+cqZO+rbpQPEBiTuyklUxyVdnqH9/A4g="

language: go

go:
  - tip

before_install:
  - echo $PROJECT_ROOT
  - mkdir -p $PROJECT_ROOT/mygo
  - export GOPATH=$PROJECT_ROOT/mygo
  - go get github.com/hashicorp/atlas-upload-cli
  - cd $GOPATH/src/github.com/hashicorp/atlas-upload-cli/
  - make


install:
    - go install


before_script:
    - cd $PROJECT_ROOT/tests/


script:
    - echo "Run Tests Here"

after_success:
    - echo "Build Successful"
    - cd $GOPATH/src/github.com/hashicorp/atlas-upload-cli/
    - ./bin/atlas-upload bitgeeky/simple $PROJECT_ROOT/app

branches:
    only:
        - master
